### ISSUE TITLE
I'm getting error

### ISSUE THREAD

**Issue by rydh22** [kylierst/MSO_E5_Dev_AutoRenew#31]
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
  python3 temp.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    Python[2](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:3).9.17/x6[4](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x[6](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.1[7](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:7)/x64/lib
  File "/home/runner/work/MSO/MSO/temp.py", line [11](https://github.com/rydh22/MSO/actions/runs/5621605044/job/15233049226#step:6:11)
    ***
          ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.

**Comment by kylierst** [comment]
Check your Github Action Secrets. There is probably a misplaced space or character thats why its giving this syntax error

**Comment by rydh22** [comment]
that got resolved, but here is another one

Run ad-m/github-push-action@v0.6.0
Started: bash /home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.sh
Push to branch refs/heads/main
To https://github.com/rydh22/MSO.git
 ! [rejected]          HEAD -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/rydh22/MSO.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (node:events:[52](https://github.com/rydh22/MSO/actions/runs/5667662527/job/15357988378#step:9:53)7:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
##[debug]Node Action run completed with exit code 1

**Comment by yo-honey** [comment]
> that got resolved, but here is another one
> 
> Run ad-m/github-push-action@v0.6.0 Started: bash /home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.sh Push to branch refs/heads/main To https://github.com/rydh22/MSO.git ! [rejected] HEAD -> main (non-fast-forward) error: failed to push some refs to 'https://github.com/rydh22/MSO.git' hint: Updates were rejected because the tip of your current branch is behind hint: its remote counterpart. Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. Error: Invalid status code: 1 at ChildProcess. (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19) at ChildProcess.emit (node:events:527:28) at maybeClose (node:internal/child_process:1092:16) at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) { code: 1 } Error: Invalid status code: 1 at ChildProcess. (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19) at ChildProcess.emit (node:events:[52](https://github.com/rydh22/MSO/actions/runs/5667662527/job/15357988378#step:9:53)7:28) at maybeClose (node:internal/child_process:1092:16) at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) ##[debug]Node Action run completed with exit code 1

Getting same error, was getting refresh token error, just updated refresh token & getting this error now, fork is synced to latest @kylierst

**Comment by wcwcwc1920** [comment]
> Check your Github Action Secrets. There is probably a misplaced space or character thats why its giving this syntax error

<img width="820" alt="9c2ff6eef709d280182d01f43eb6a14" src="https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/39624149/90fe377e-72f8-4135-b392-caf795a72908">
 
who can help me    it's right?
