### ISSUE TITLE
It was working fine but now I am getting an KeyError

### ISSUE THREAD

**Issue by jaum20** [kylierst/MSO_E5_Dev_AutoRenew#33]
I was using this successfully for three months but now I am getting this error:

```
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
Traceback (most recent call last):
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 70, in <module>
    main()
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 50, in main
    access_token = get_access_token(refresh_token, client_id, client_secret)
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 45, in get_access_token
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.
```
How can I fix this? Do I need to sync my fork with kylierst original repo?

**Comment by kylierst** [comment]
Get a new refresh token from rclone

**Comment by jaum20** [comment]
Didn't work :/

The token is working with rclone
