### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by spenzeil** [kylierst/MSO_E5_Dev_AutoRenew#35]
I keep on getting this error despite always getting the refresh_token thru rclone

 File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 83, in <module>
    main()
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 62, in main
    access_token = get_access_token(refresh_token, client_id, client_secret)
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 55, in get_access_token
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.

**Comment by kylierst** [comment]
Please make sure there is nothing wrong in your Github Action Secrets
your refresh token when entered should look like this 

refresh_token=r'[paste your refresh token here]'

remove the brackets

**Comment by doomwithdon** [comment]
https://github.com/kylierst/MSO_E5_Dev_AutoRenew/issues/40#issuecomment-1709383695

**Comment by dsakura** [comment]
Me too.. I redo the rclone steps to generate a new refresh_token, redo the gith_token too.. same error.
`Traceback (most recent call last):
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 83, in <module>
    main()
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 62, in main
    access_token = get_access_token(refresh_token, client_id, client_secret)
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 55, in get_access_token
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code 1.`

Thanks!
